/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface DkTab {
    'label': string;
  }
  interface DkTabAttributes extends StencilHTMLAttributes {
    'label'?: string;
  }

  interface DkTabs {
    /**
    * Index of the selected tab.
    */
    'selected': number;
  }
  interface DkTabsAttributes extends StencilHTMLAttributes {
    /**
    * Index of the selected tab.
    */
    'selected'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'DkTab': Components.DkTab;
    'DkTabs': Components.DkTabs;
  }

  interface StencilIntrinsicElements {
    'dk-tab': Components.DkTabAttributes;
    'dk-tabs': Components.DkTabsAttributes;
  }


  interface HTMLDkTabElement extends Components.DkTab, HTMLStencilElement {}
  var HTMLDkTabElement: {
    prototype: HTMLDkTabElement;
    new (): HTMLDkTabElement;
  };

  interface HTMLDkTabsElement extends Components.DkTabs, HTMLStencilElement {}
  var HTMLDkTabsElement: {
    prototype: HTMLDkTabsElement;
    new (): HTMLDkTabsElement;
  };

  interface HTMLElementTagNameMap {
    'dk-tab': HTMLDkTabElement
    'dk-tabs': HTMLDkTabsElement
  }

  interface ElementTagNameMap {
    'dk-tab': HTMLDkTabElement;
    'dk-tabs': HTMLDkTabsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
