/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface TodomvcStencil {}
  interface TodomvcStencilAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'TodomvcStencil': Components.TodomvcStencil;
  }

  interface StencilIntrinsicElements {
    'todomvc-stencil': Components.TodomvcStencilAttributes;
  }


  interface HTMLTodomvcStencilElement extends Components.TodomvcStencil, HTMLStencilElement {}
  var HTMLTodomvcStencilElement: {
    prototype: HTMLTodomvcStencilElement;
    new (): HTMLTodomvcStencilElement;
  };

  interface HTMLElementTagNameMap {
    'todomvc-stencil': HTMLTodomvcStencilElement
  }

  interface ElementTagNameMap {
    'todomvc-stencil': HTMLTodomvcStencilElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
