/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  Todo,
} from './todo';


export namespace Components {

  interface TodoApp {}
  interface TodoAppAttributes extends StencilHTMLAttributes {}

  interface TodoList {
    'todos': Todo[];
  }
  interface TodoListAttributes extends StencilHTMLAttributes {
    'onEditTitle'?: (event: CustomEvent) => void;
    'onTodoDeleted'?: (event: CustomEvent) => void;
    'onToggleAll'?: (event: CustomEvent) => void;
    'onToggleCompleted'?: (event: CustomEvent) => void;
    'todos'?: Todo[];
  }
}

declare global {
  interface StencilElementInterfaces {
    'TodoApp': Components.TodoApp;
    'TodoList': Components.TodoList;
  }

  interface StencilIntrinsicElements {
    'todo-app': Components.TodoAppAttributes;
    'todo-list': Components.TodoListAttributes;
  }


  interface HTMLTodoAppElement extends Components.TodoApp, HTMLStencilElement {}
  var HTMLTodoAppElement: {
    prototype: HTMLTodoAppElement;
    new (): HTMLTodoAppElement;
  };

  interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {}
  var HTMLTodoListElement: {
    prototype: HTMLTodoListElement;
    new (): HTMLTodoListElement;
  };

  interface HTMLElementTagNameMap {
    'todo-app': HTMLTodoAppElement
    'todo-list': HTMLTodoListElement
  }

  interface ElementTagNameMap {
    'todo-app': HTMLTodoAppElement;
    'todo-list': HTMLTodoListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
